<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Slim 3</title>
        <link rel="stylesheet" href="http://yegor256.github.io/tacit/tacit.min.css">
    </head>
    <body>
        <!-- make sure the attribute enctype is set to multipart/form-data -->
        <form method="post" enctype="multipart/form-data">
            <!-- upload of a single file -->
            <!-- <p>
                <label>Add file (single): </label><br/>
                <input type="file" name="example1"/>
            </p> -->

            <!-- multiple input fields for the same input name, use brackets -->
            <!-- <p>
                <label>Add files (up to 2): </label><br/>
                <input type="file" name="example2[]"/><br/>
                <input type="file" name="example2[]"/>
            </p> -->

            <!-- one file input field that allows multiple files to be uploaded, use brackets -->
            <p>
                <label>ファイル選択 (複数選択可　最大サイズ120Mまで): </label><br/>
                <input type="file" name="example3[]" multiple="multiple"/>
            </p>

            <p>
                <input type="submit"/>
            </p>
        </form>
    </body>
</html>